# Cloudflare Workers Configuration for Edge Caching
# Deploy with: wrangler deploy

name = "prompt-builder-edge-cache"
main = "cloudflare-worker.js"
compatibility_date = "2024-01-01"

# Workers AI account (update with your account details)
# Get your account_id from: https://dash.cloudflare.com
account_id = "YOUR_CLOUDFLARE_ACCOUNT_ID"

# Route configuration
# Option 1: Use a custom domain
# routes = [
#   { pattern = "api.yourapp.com/*", zone_id = "YOUR_ZONE_ID" }
# ]

# Option 2: Use workers.dev subdomain
workers_dev = true

# Environment variables
[env.production]
vars = { ORIGIN_URL = "https://your-production-server.com" }

[env.staging]
vars = { ORIGIN_URL = "https://your-staging-server.com" }

[env.development]
vars = { ORIGIN_URL = "http://localhost:3001" }

# Limits and performance
# These values are optimized for the span labeling use case
[limits]
cpu_ms = 50  # Max CPU time per request (default: 50ms)

# Cron triggers for cache warming (optional)
# [triggers]
# crons = ["0 */6 * * *"]  # Every 6 hours

# KV namespace for analytics (optional)
# [[kv_namespaces]]
# binding = "CACHE_ANALYTICS"
# id = "your-kv-namespace-id"

# Durable Objects for distributed cache coordination (optional)
# [[durable_objects.bindings]]
# name = "CACHE_COORDINATOR"
# class_name = "CacheCoordinator"
# script_name = "prompt-builder-edge-cache"
