export type CoverageCategory = {
  key: string;
  label: string;
  colorClass: string;
  words: readonly string[];
};

export const COVERAGE_CATEGORIES: readonly CoverageCategory[] = [
  {
    key: 'subject',
    label: 'Subject',
    colorClass: 'bg-accent-2/40',
    words: [
      'person',
      'woman',
      'man',
      'child',
      'face',
      'hands',
      'robot',
      'creature',
      'car',
      'city',
      'forest',
      'mountain',
      'ocean',
      'room',
      'street',
      'table',
      'product',
      'logo',
    ],
  },
  {
    key: 'camera',
    label: 'Camera',
    colorClass: 'bg-accent-2/30',
    words: [
      'wide',
      'close',
      'close-up',
      'macro',
      'dolly',
      'tracking',
      'handheld',
      'crane',
      'gimbal',
      'pan',
      'tilt',
      'zoom',
      'orbit',
      'lens',
      '35mm',
      '50mm',
      'anamorphic',
      'shallow depth',
      'deep focus',
    ],
  },
  {
    key: 'lighting',
    label: 'Lighting',
    colorClass: 'bg-accent-2/25',
    words: [
      'soft',
      'hard',
      'backlit',
      'rim light',
      'key light',
      'fill',
      'neon',
      'golden hour',
      'sunset',
      'studio',
      'moody',
      'high contrast',
      'low key',
      'volumetric',
      'fog',
      'glow',
    ],
  },
  {
    key: 'motion',
    label: 'Motion',
    colorClass: 'bg-accent-2/20',
    words: [
      'slow motion',
      'timelapse',
      'speed ramp',
      'walking',
      'running',
      'spinning',
      'floating',
      'drifting',
      'wind',
      'waves',
      'swirling',
      'shake',
      'vibration',
      'push in',
      'pull back',
    ],
  },
  {
    key: 'style',
    label: 'Style',
    colorClass: 'bg-accent-2/15',
    words: [
      'cinematic',
      'film',
      'documentary',
      'noir',
      'anime',
      '3d',
      'photoreal',
      'surreal',
      'vintage',
      'minimal',
      'brutalist',
      'cyberpunk',
      'watercolor',
      'illustration',
      'grain',
    ],
  },
];

export const WORKFLOW_CHIP_STORAGE_KEY = 'po:workflowChipSeen';
