# Alertmanager Configuration
#
# Routes alerts to various receivers (Slack, email, PagerDuty, etc.)

global:
  resolve_timeout: 5m

# Route tree
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  receiver: 'default'

  # Child routes
  routes:
    # Critical alerts - immediate notification
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 0s
      repeat_interval: 5m

    # Warning alerts - less frequent notifications
    - match:
        severity: warning
      receiver: 'warning-alerts'
      repeat_interval: 30m

# Receivers (notification channels)
receivers:
  # Default receiver (logs only)
  - name: 'default'
    webhook_configs:
      - url: 'http://localhost:9093/api/v1/webhook'

  # Critical alerts (configure your notification channel)
  - name: 'critical-alerts'
    # Slack example:
    # slack_configs:
    #   - api_url: 'YOUR_SLACK_WEBHOOK_URL'
    #     channel: '#alerts-critical'
    #     title: 'Critical Alert'
    #     text: '{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}'

    # Email example:
    # email_configs:
    #   - to: 'oncall@yourcompany.com'
    #     from: 'alertmanager@yourcompany.com'
    #     smarthost: 'smtp.gmail.com:587'
    #     auth_username: 'your@email.com'
    #     auth_password: 'your-password'

    # PagerDuty example:
    # pagerduty_configs:
    #   - service_key: 'YOUR_PAGERDUTY_SERVICE_KEY'

    webhook_configs:
      - url: 'http://localhost:9093/api/v1/webhook'

  # Warning alerts
  - name: 'warning-alerts'
    webhook_configs:
      - url: 'http://localhost:9093/api/v1/webhook'

# Inhibit rules (suppress alerts based on other alerts)
inhibit_rules:
  # Suppress warning alerts if critical alert is firing
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']
