import type { ApiErrorCode } from '@server/types/apiError';

export const GENERATION_ERROR_CODES = {
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  INVALID_REQUEST: 'INVALID_REQUEST',
  INSUFFICIENT_CREDITS: 'INSUFFICIENT_CREDITS',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  GENERATION_FAILED: 'GENERATION_FAILED',
  IDEMPOTENCY_KEY_REQUIRED: 'IDEMPOTENCY_KEY_REQUIRED',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',
  REQUEST_IN_PROGRESS: 'REQUEST_IN_PROGRESS',
} as const satisfies Record<string, ApiErrorCode>;
