apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

commonLabels:
  app: prompt-builder
  managed-by: kustomize

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml
  - serviceaccount.yaml

images:
  - name: ghcr.io/bharm16/prompt-builder
    newTag: latest
