apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: prompt-builder-api-pdb
  labels:
    app: prompt-builder
spec:
  minAvailable: 2  # Always keep at least 2 pods running
  selector:
    matchLabels:
      app: prompt-builder
      component: api
