apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  args:
    - name: service-name
    - name: prometheus-url
      value: http://prometheus.monitoring:9090
  metrics:
    - name: success-rate
      interval: 1m
      successCondition: result >= 0.95
      failureLimit: 3
      provider:
        prometheus:
          address: "{{args.prometheus-url}}"
          query: |
            sum(rate(
              http_requests_total{
                service="{{args.service-name}}",
                status=~"2.."
              }[5m]
            )) /
            sum(rate(
              http_requests_total{
                service="{{args.service-name}}"
              }[5m]
            ))
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: latency
spec:
  args:
    - name: service-name
    - name: prometheus-url
      value: http://prometheus.monitoring:9090
  metrics:
    - name: p95-latency
      interval: 1m
      successCondition: result <= 1000  # 1 second
      failureLimit: 3
      provider:
        prometheus:
          address: "{{args.prometheus-url}}"
          query: |
            histogram_quantile(0.95,
              sum(rate(
                http_request_duration_milliseconds_bucket{
                  service="{{args.service-name}}"
                }[5m]
              )) by (le)
            )
    - name: p99-latency
      interval: 1m
      successCondition: result <= 2000  # 2 seconds
      failureLimit: 3
      provider:
        prometheus:
          address: "{{args.prometheus-url}}"
          query: |
            histogram_quantile(0.99,
              sum(rate(
                http_request_duration_milliseconds_bucket{
                  service="{{args.service-name}}"
                }[5m]
              )) by (le)
            )
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: error-rate
spec:
  args:
    - name: service-name
    - name: prometheus-url
      value: http://prometheus.monitoring:9090
  metrics:
    - name: error-rate
      interval: 1m
      successCondition: result <= 0.05  # Max 5% error rate
      failureLimit: 3
      provider:
        prometheus:
          address: "{{args.prometheus-url}}"
          query: |
            sum(rate(
              http_requests_total{
                service="{{args.service-name}}",
                status=~"5.."
              }[5m]
            )) /
            sum(rate(
              http_requests_total{
                service="{{args.service-name}}"
              }[5m]
            ))
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: memory-usage
spec:
  args:
    - name: service-name
    - name: prometheus-url
      value: http://prometheus.monitoring:9090
  metrics:
    - name: memory-usage
      interval: 1m
      successCondition: result <= 0.9  # Max 90% of limit
      failureLimit: 5
      provider:
        prometheus:
          address: "{{args.prometheus-url}}"
          query: |
            sum(
              container_memory_usage_bytes{
                pod=~"{{args.service-name}}.*"
              }
            ) /
            sum(
              container_spec_memory_limit_bytes{
                pod=~"{{args.service-name}}.*"
              }
            )
