apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prompt-builder-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: prompt-builder-deployments
    notifications.argoproj.io/subscribe.on-sync-failed.slack: prompt-builder-alerts
spec:
  project: default

  source:
    repoURL: https://github.com/bharm16/prompt-builder.git
    targetRevision: HEAD  # Use tags for production
    path: k8s/overlays/production

  destination:
    server: https://kubernetes.default.svc
    namespace: production

  syncPolicy:
    # Manual sync for production - requires approval
    automated: null
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m

  # Health checks
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas  # Ignore HPA-managed replica count

  revisionHistoryLimit: 30

  # Sync windows - prevent deployments during business hours
  syncWindows:
    - kind: allow
      schedule: '0 0-6,20-23 * * *'  # Only allow deploys outside 7am-8pm
      duration: 1h
      applications:
        - prompt-builder-production
      timeZone: America/New_York
