#!/usr/bin/env node
/**
 * Generate a Markdown table of all server HTTP routes by walking the Express
 * route registration code with the TypeScript compiler API.
 *
 * Usage:
 *   npx tsx scripts/generate-route-map.ts               # print to stdout
 *   npx tsx scripts/generate-route-map.ts --check       # exit non-zero if ROUTE_MAP.md is stale
 *   npx tsx scripts/generate-route-map.ts --write       # rewrite docs/architecture/ROUTE_MAP.md
 *
 * Source of truth:
 *   - server/src/app.ts, server/src/config/routes.config.ts, server/src/config/routes/*.ts
 *     for top-level `app.use("/prefix", <factory>)` mounts
 *   - server/src/routes/**\/*.ts for the router definitions themselves
 *
 * The walker recognizes three patterns per exported function body:
 *   router.<method>("/path", ...)           -> emits an endpoint under the caller's prefix
 *   router.use("/sub", <factoryCall>)       -> descends into the sub-router under /sub
 *   register<X>Route(router, ...)           -> inlines endpoints from the register fn
 *
 * Gated conditional blocks (`if (foo) { router.use(...) }`) are still expanded because
 * the goal is to enumerate every route the server *can* register, not what it *does*
 * register on a given process configuration.
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import {
  extractRoutes,
  REPO_ROOT,
  type RouteEntry,
} from "./lib/route-map-walker.ts";

const ROUTE_MAP_PATH = path.join(
  REPO_ROOT,
  "docs",
  "architecture",
  "ROUTE_MAP.md",
);

function renderMarkdown(entries: RouteEntry[]): string {
  const lines: string[] = [];
  lines.push("# Route Map");
  lines.push("");
  lines.push(
    "<!-- Auto-generated by scripts/generate-route-map.ts. Do not edit by hand. -->",
  );
  lines.push(
    "<!-- Source of truth: server/src/routes/**/*.ts + server/src/config/routes/*.ts -->",
  );
  lines.push("");
  lines.push(
    "Regenerate with `npm run routemap:generate`. CI enforces freshness via `npm run routemap:check`.",
  );
  lines.push("");

  const header = ["Method", "Full path", "Source file"];
  const rows: string[][] = [header];
  for (const entry of entries) {
    rows.push([
      entry.method,
      `\`${entry.fullPath}\``,
      `\`${entry.sourceFile}\``,
    ]);
  }
  const widths = header.map((_, col) =>
    rows.reduce((max, r) => Math.max(max, r[col]?.length ?? 0), 0),
  );
  const pad = (cells: string[]): string =>
    `| ${cells.map((c, i) => c.padEnd(widths[i] ?? 0)).join(" | ")} |`;
  const separator = `| ${widths.map((w) => "-".repeat(Math.max(w, 3))).join(" | ")} |`;
  lines.push(pad(rows[0]!));
  lines.push(separator);
  for (const row of rows.slice(1)) lines.push(pad(row));
  lines.push("");
  lines.push(
    `_Generated route count: **${entries.length}**. Each row reflects a real ` +
      "`router.<method>` call reachable from `app.use` at server boot; conditional " +
      "registrations (feature-flagged routes) are included because they can be " +
      "registered under some configuration._",
  );
  lines.push("");
  return lines.join("\n");
}

function main(): void {
  const args = new Set(process.argv.slice(2));
  const entries = extractRoutes();
  const rendered = renderMarkdown(entries);

  if (args.has("--check")) {
    const onDisk = fs.existsSync(ROUTE_MAP_PATH)
      ? fs.readFileSync(ROUTE_MAP_PATH, "utf8")
      : "";
    if (onDisk !== rendered) {
      process.stderr.write(
        `ROUTE_MAP.md is stale. Run: npm run routemap:generate\n` +
          `  Expected ${entries.length} routes on disk.\n`,
      );
      process.exit(1);
    }
    process.stdout.write(
      `ROUTE_MAP.md is current (${entries.length} routes).\n`,
    );
    return;
  }

  if (args.has("--write")) {
    fs.mkdirSync(path.dirname(ROUTE_MAP_PATH), { recursive: true });
    const existing = fs.existsSync(ROUTE_MAP_PATH)
      ? fs.readFileSync(ROUTE_MAP_PATH, "utf8")
      : "";
    if (existing === rendered) {
      process.stdout.write(
        `ROUTE_MAP.md already current (${entries.length} routes).\n`,
      );
      return;
    }
    fs.writeFileSync(ROUTE_MAP_PATH, rendered, "utf8");
    process.stdout.write(
      `ROUTE_MAP.md rewritten (${entries.length} routes).\n`,
    );
    return;
  }

  // Default: print to stdout
  process.stdout.write(rendered);
}

const isMain =
  import.meta.url === `file://${process.argv[1]}` ||
  (process.argv[1] !== undefined && import.meta.url.endsWith(process.argv[1]));

if (isMain) {
  main();
}
