#!/usr/bin/env node
/**
 * Generate a Markdown table of all server feature flags from the registry.
 *
 * Usage:
 *   npx tsx scripts/generate-flag-docs.ts               # print to stdout
 *   npx tsx scripts/generate-flag-docs.ts --check       # exit non-zero if CLAUDE.md table is stale
 *   npx tsx scripts/generate-flag-docs.ts --write       # rewrite the table block in CLAUDE.md
 *
 * The CLAUDE.md table lives between the markers:
 *   <!-- BEGIN: feature-flag-table -->
 *   <!-- END: feature-flag-table -->
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import {
  getFlagEnvNames,
  type FlagCategory,
} from "../server/src/config/feature-flags.ts";

const REPO_ROOT = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
);
const CLAUDE_MD = path.join(REPO_ROOT, "CLAUDE.md");
const BEGIN_MARKER = "<!-- BEGIN: feature-flag-table -->";
const END_MARKER = "<!-- END: feature-flag-table -->";

const CATEGORY_ORDER: FlagCategory[] = [
  "mode",
  "worker",
  "killswitch",
  "provider",
  "experimental",
  "debug",
];

function renderTable(): string {
  const flags = getFlagEnvNames();
  const byCategory = new Map<FlagCategory, typeof flags>();
  for (const f of flags) {
    const bucket = byCategory.get(f.category) ?? [];
    bucket.push(f);
    byCategory.set(f.category, bucket);
  }

  const lines: string[] = [];
  lines.push(BEGIN_MARKER);
  lines.push("");
  lines.push(
    "<!-- Auto-generated by scripts/generate-flag-docs.ts. Do not edit by hand. -->",
  );
  lines.push("<!-- Source of truth: server/src/config/feature-flags.ts -->");
  lines.push("");

  for (const category of CATEGORY_ORDER) {
    const group = byCategory.get(category);
    if (!group || group.length === 0) continue;

    lines.push(`#### ${category.charAt(0).toUpperCase() + category.slice(1)}`);
    lines.push("");
    // Build rows as arrays, then column-align so the output matches what
    // prettier's Markdown formatter would produce. Without this, `npm run
    // format` rewrites the table and --check mode flags false staleness.
    const header = ["Env Var", "Default", "Legacy Aliases", "Description"];
    const rows: string[][] = [header];
    for (const f of group) {
      const aliases =
        f.aliases.length === 0
          ? "—"
          : f.aliases.map((a) => `\`${a}\``).join(", ");
      rows.push([
        `\`${f.envName}\``,
        `\`${f.defaultValue}\``,
        aliases,
        f.description,
      ]);
    }
    const widths = header.map((_, col) =>
      rows.reduce((max, r) => Math.max(max, r[col]?.length ?? 0), 0),
    );
    const pad = (cells: string[]): string =>
      `| ${cells.map((c, i) => c.padEnd(widths[i] ?? 0)).join(" | ")} |`;
    const separator = `| ${widths.map((w) => "-".repeat(Math.max(w, 3))).join(" | ")} |`;
    lines.push(pad(rows[0]!));
    lines.push(separator);
    for (const row of rows.slice(1)) lines.push(pad(row));
    lines.push("");
  }

  lines.push(END_MARKER);
  return lines.join("\n");
}

function rewriteClaudeMd(): { changed: boolean; updated: string } {
  const current = fs.readFileSync(CLAUDE_MD, "utf8");
  const table = renderTable();

  const beginIdx = current.indexOf(BEGIN_MARKER);
  const endIdx = current.indexOf(END_MARKER);

  let updated: string;
  if (beginIdx === -1 || endIdx === -1 || endIdx < beginIdx) {
    // No existing block — append one near the Feature Flags heading.
    const anchor = "## Feature Flags";
    const anchorIdx = current.indexOf(anchor);
    if (anchorIdx === -1) {
      throw new Error(
        `CLAUDE.md is missing the "${anchor}" heading; cannot place the generated table.`,
      );
    }
    const insertAt = current.indexOf("\n\n", anchorIdx + anchor.length) + 2;
    updated =
      current.slice(0, insertAt) + table + "\n\n" + current.slice(insertAt);
  } else {
    const endOfEnd = endIdx + END_MARKER.length;
    updated = current.slice(0, beginIdx) + table + current.slice(endOfEnd);
  }

  return { changed: updated !== current, updated };
}

function main(): void {
  const args = new Set(process.argv.slice(2));
  const table = renderTable();

  if (args.has("--write")) {
    const { changed, updated } = rewriteClaudeMd();
    if (changed) {
      fs.writeFileSync(CLAUDE_MD, updated, "utf8");
      process.stdout.write("CLAUDE.md feature-flag table updated.\n");
    } else {
      process.stdout.write(
        "CLAUDE.md feature-flag table is already current.\n",
      );
    }
    return;
  }

  if (args.has("--check")) {
    const { changed } = rewriteClaudeMd();
    if (changed) {
      process.stderr.write(
        "CLAUDE.md feature-flag table is stale. Run: npx tsx scripts/generate-flag-docs.ts --write\n",
      );
      process.exit(1);
    }
    process.stdout.write("CLAUDE.md feature-flag table is current.\n");
    return;
  }

  process.stdout.write(`${table}\n`);
}

main();
