apiVersion: apps/v1
kind: Deployment
metadata:
  name: prompt-builder-api
spec:
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
    spec:
      # Stricter affinity rules for production
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - prompt-builder
              topologyKey: kubernetes.io/hostname
      containers:
        - name: api
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
