apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

bases:
  - ../../base

namePrefix: prod-

commonLabels:
  environment: production

replicas:
  - name: prompt-builder-api
    count: 5  # More replicas in production

images:
  - name: ghcr.io/bharm16/prompt-builder
    newTag: v1.0.0  # Use specific version tag in production

patchesStrategicMerge:
  - deployment-patch.yaml
  - hpa-patch.yaml
  - configmap-patch.yaml

configMapGenerator:
  - name: prompt-builder-config
    behavior: merge
    literals:
      - LOG_LEVEL=warn
      - ALLOWED_ORIGINS=https://prompt-builder.example.com,https://www.prompt-builder.example.com
      - FRONTEND_URL=https://prompt-builder.example.com
