apiVersion: v1
kind: ServiceAccount
metadata:
  name: prompt-builder-api
  labels:
    app: prompt-builder
  annotations:
    # For AWS IAM role association (IRSA)
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/prompt-builder-api-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prompt-builder-api
  labels:
    app: prompt-builder
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prompt-builder-api
  labels:
    app: prompt-builder
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prompt-builder-api
subjects:
  - kind: ServiceAccount
    name: prompt-builder-api
    namespace: default
