apiVersion: apps/v1
kind: Deployment
metadata:
  name: prompt-builder-api
spec:
  template:
    spec:
      containers:
        - name: api
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
